apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo-chart
      version: 6.6.2
  values:
    replicaCount: 1
  interval: 1m0s
